language: ruby
rvm:
  - 2.1.0
env:
  - JIRA_URL="jira.example.org"
  - JIRA_USERNAME="travis"
  - JIRA_PASSWORD="abc123"
  - JIRA_URL_FILE="/home/travis/.jira_url"
  - JIRA_AUTH_FILE="/home/travis/.jira_auth"
install: ./build.sh
script: rspec
notifications:
  email:
    on_success: never
    on_failure: change
